# Generated by Django 3.2.4 on 2021-06-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_stdsign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stdsign',
            new_name='stdsignin',
        ),
    ]
