# Generated by Django 3.2.4 on 2021-06-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_stdregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='addstd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('stdname', models.CharField(max_length=100)),
                ('stdid', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
                ('cls', models.CharField(max_length=100)),
                ('sec', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
