# Generated by Django 3.2.4 on 2021-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_addstd'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('cd', models.CharField(max_length=100)),
            ],
        ),
    ]
