# Generated by Django 3.2.4 on 2021-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=100)),
                ('clgname', models.CharField(max_length=100)),
                ('cd', models.CharField(max_length=100)),
            ],
        ),
    ]
