# Generated by Django 3.2.4 on 2021-06-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='cd',
            new_name='clgd',
        ),
    ]
