# Generated by Django 3.2.4 on 2021-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_auto_20210628_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdregister',
            name='pschool',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
